# SPDX-License-Identifier: GPL-2.0-only
# Makefile for Qualcomm CAMSS driver

qcom-camss-objs += \
		camss.o \
		camss-csid.o \
		camss-csid-4-1.o \
		camss-csid-4-7.o \
		camss-csid-340.o \
		camss-csid-680.o \
		camss-csid-gen2.o \
		camss-csid-gen3.o \
		camss-csiphy-2ph-1-0.o \
		camss-csiphy-3ph-1-0.o \
		camss-csiphy.o \
		camss-ispif.o \
		camss-vfe-4-1.o \
		camss-vfe-4-7.o \
		camss-vfe-4-8.o \
		camss-vfe-17x.o \
		camss-vfe-340.o \
		camss-vfe-480.o \
		camss-vfe-680.o \
		camss-vfe-gen3.o \
		camss-vfe-gen1.o \
		camss-vfe-vbif.o \
		camss-vfe.o \
		camss-video.o \
		camss-format.o \

obj-$(CONFIG_VIDEO_QCOM_CAMSS) += qcom-camss.o

qcom-camss-icp-objs += camss-icp.o \
		       camss-icp-hfi.o
obj-$(CONFIG_VIDEO_QCOM_CAMSS_HARD_ISP) += qcom-camss-icp.o

qcom-camss-bps-objs += camss-bps.o \
		       camss-bps-cmd.o
obj-$(CONFIG_VIDEO_QCOM_CAMSS_HARD_ISP) += qcom-camss-bps.o
